### ISSUE TITLE
Warum den absoluten Pfad nutzen?

### ISSUE THREAD

**Issue by hvorragend** [JoschaMiddendorf/fhem-docker#29]
Hallo,

mit purer Begeisterung bin ich gerade über dein Projekt hier gestolpert und habe direkt ein paar Ideen bei mir eingebaut. Absolut genial. Vielen Dank.

Aber wieso erwähnst du, dass man vorzugsweise absolute Pfade nutzen sollte?

> Make shure to always use absolout paths in your fhem.cfg beginning with /opt/fhem/ not with ./ !

Ich habe das bei mir nicht gemacht und es scheint dennoch zu funktionieren. Habe ich etwas übersehen? Danke für die Antwort.

_(Am Rande - kleine Typos: Make sure to always use absolute ...)_

**Comment by JoschaMiddendorf** [comment]
Hallo,
freut mich das du den Container für dich nutzen kannst. Wenn du Ideen zur Verbesserung hast, immer her damit, gerne hier als Vorschlag oder auch direkt als pull request. Mein Anliegen ist es diesen Container mit fhem wachsen zu lassen und immer eine optimale Umgebung zu bieten im alle Features von fhem nutzen zu können. 

Ich hatte mal Probleme mit relativen Pfaden. Ich glaube mit dem log Output während eines Updates. Absolute Pfade haben da geholfen. Es kann aber auch sein das es mittlerweile mit relativen Pfaden problemfrei läuft. 

Wo kann ich dein Projekt finden?

**Comment by hvorragend** [comment]
Hallo Joscha, ich habe mein Projekt nur lokal liegen. 
Mehrere Monate habe ich geprobt und mit Docker Erfahrungen gesammelt. Ende 2017 bin ich dann mit FHEM & Co. vollends umgestiegen und bin enorm begeistert.

Meine Dockerfiles und Startskripte sind auch recht übersichtlich. Meine docker-compose.yml ist jedoch komplex geworden:

- fhem
- samba
- nginx-letsencrypt
- nginx-gen
- nginx
- ha-bridge
- homebridge
- ebusd
- sonos
- lepresenced
- mqtt
- mysql
- hmcfgusb

Mal schauen, ob ich das irgendwann mal zusammenfüge und auf DockerHub veröffentliche. 

Mir gefällt deine Variante des Startskripts (StartAndInitialize.sh). Es läuft perfekt und der Container überlebt sogar Neustarts. Im folgenden Thread wurde das auch thematisiert: https://forum.fhem.de/index.php/topic,87052.msg795033.html

---

Ich habe im Global-Device testweise auch mal auf absolute Pfade umgestellt. Es tut ja nicht weh und es ändert sich nichts zum Negativen.
