### ISSUE TITLE
FHEM seems to start twice

### ISSUE THREAD

**Issue by JoschaMiddendorf** [JoschaMiddendorf/fhem-docker#3]
FHEM seems to start twice

...
2018.02.15 00:23:14 0: Server shutdown
2018.02.15 00:23:15 5: Initializing Type Library:
2018.02.15 00:23:15 1: Including fhem.cfg
...
2018.02.15 00:23:16 5: Initializing Type Library:
2018.02.15 00:23:16 1: Including fhem.cfg
...

**Comment by stauraum** [comment]
add "attr global nofork 1" to your fhem.cfg

**Comment by JoschaMiddendorf** [comment]
solved by release 0.10.0
