### ISSUE TITLE
Installation auf Synology - kein Update

### ISSUE THREAD

**Issue by ottoplanet** [JoschaMiddendorf/fhem-docker#30]
Hallo,

ich will derzeit auch mein Raspi einmotten und ein Docker FHEM auf meiner Synology Diskstation laufen lassen. Leider scheinen die FHEM Dockerimages auf der Diskstation keine Namensauflösung zu beherrschen. Ein Updatebfehl oder das Wettermodul von Yahoo (gethostbyname query.yahooapis.com failed) funktionieren daher nicht, Weißt Du dafür evtl. eine Lösung? 

Gruß Andreas

**Comment by JoschaMiddendorf** [comment]
Ich nutze das Yahoo Wetter modul ebenfalls, habe den Container allerdings auf einem unraid Host laufen. Poste doch mal den log Output mit verbose 5 von der problematik. Vielleicht fällt mir ja was auf.

**Comment by ottoplanet** [comment]
Hallo,
ich habe mal das Log angehängt...

Mir fällt leider erst mal nichts auf.

Gruß Andreas

[fhem-2018-04.log](https://github.com/JoschaMiddendorf/fhem-docker/files/1960364/fhem-2018-04.log)

**Comment by ottoplanet** [comment]
Hallo,

ich konnte mein Problem selbst lösen. Die Synology Firewall war nicht richtig konfiguriert.
Hier der Link vom Synology Forum der mir auf die Sprünge geholfen hat -> (https://www.synology-forum.de/showthread.html?82660-Docker-Container-hat-keinen-Zugriff-auf-das-Internet-bei-aktiver-Firewall)

Gruß Andreas

**Comment by JoschaMiddendorf** [comment]
Freut mich das es nun klappt. Ich hoffe du bist ansonsten mit meinem container zufrieden und kannst ihn nun lückenlos nutzen. Wenn es sonst Fragen, Wünsche, Anregungen oder Verbesserungsvorschläge gibt mach gerne wieder einen Issue auf.
Gruß Joscha
