### ISSUE TITLE
Einrichtung des FHEM moduls MOBILEALERTSGW

### ISSUE THREAD

**Issue by ottoplanet** [JoschaMiddendorf/fhem-docker#33]
Hallo,

verwendet jemand das MOBILEALERTSGW in FHEM?.
Da der Docker Container ja eine eigene IP Adresse hat, die jedenfalls bei Synology nichts mit dem normalen Netz zu tun hat, weiß ich nicht, welche Proxy-Adresse ich eintragen muß?

Hat jemand eine Idee?

Gruß Andreas

**Comment by JoschaMiddendorf** [comment]
Du erreichst den Container in der Regel über die IP Adresse vom Host also der deiner diskstation und dann über den standart Port 8083. die Docker internen IP Adressen sind nur für die Kommunikation zwischen unterschiedlichen Docker Containern gedacht. 
Edit: Port 8083 musst du natürlich in deinen Container Einstellungen auf der DS an den Container durchreichen.

**Comment by ottoplanet** [comment]
Danke,
ich dachte, da muß etwas Besonderes eingetragen werden, da ja in FHEM ein Proxyserver estellt wird.

Nun geht aber alles.

Gruß Andreas
