### ISSUE TITLE
Add prerequisites for fronthem installation

### ISSUE THREAD

**Issue by trasrikgaldifei** [JoschaMiddendorf/fhem-docker#34]
Hi Josha,

great work you did on that FHEM container! Thx a lot!
Could you please add prerequisites for fronthem installation as described on [this](https://wiki.fhem.de/wiki/Fronthem_Installation) wiki page?

- cpanmin
- Websocket
- JSON

Best regards,
Joachim

**Comment by JoschaMiddendorf** [comment]
Hey no problem,
libjson-perl was already installed and Net::WebSocket::Server as well as cpanminus has ben added to the beta branch. Give it a try and post feedback if everything works. The Container update will be available in just a few minutes.

**Comment by JoschaMiddendorf** [comment]
Update is available diggewuff/fhem-docker:beta

**Comment by trasrikgaldifei** [comment]
Thx for the quick response. I´ve pulled the new image, but I first have to get my fronthem/smartvisu installation up and running again (my RaspberryPi´s SD card has a segmentation fault and I have to start again from backups). I hope, I will get this running again today on my UNRAID server and will leave you feedback as soon as possible.

**Comment by trasrikgaldifei** [comment]
Seems to be working fine. In my opinion you can move this into the latest stream.
Thx again for your quick support.

**Comment by JoschaMiddendorf** [comment]
No problem, 
thumbs up for using UnRaid, best server os in my opinion. I'll give it a week or so to se if anybody encounters any issues and push it to master then. But there is no disadvantage on using the beta, at the momentaner are no experimental things inside.

**Comment by JoschaMiddendorf** [comment]
Finally pushed everything to the master branch.
Thanks again for your request.
