### ISSUE TITLE
Normales Theme 

### ISSUE THREAD

**Issue by smeeeeagain** [JoschaMiddendorf/fhem-docker#37]
Erstmal danke für den Container! 

Ist es auch möglich den mit der normalen UI zu bekommen?

Die voreingestellte ist nicht so mein Ding und wenn ich "dark" aktiviere ist es immernoch nicht aus normal.

lg

**Comment by JoschaMiddendorf** [comment]
Du kannst die Zeile 
`https://raw.githubusercontent.com/klein0r/fhem-style-haus-automatisierung/version-2/controls_ha_theme.txt`
aus der Datei /opt/fhem/FHEM/controls.txt
z.b. mit `nano /opt/fhem/FHEM/controls.txt`  entfernen (speichern mit ctrl + x -> y), 
und dann den Ordner /opt/fhem/www/hausautomatisierung-com 
z.b. mit `rm -rf /opt/fhem/www/hausautomatisierung-com/`
komplett löschen,
dann noch die attribute
`attr WEB JavaScripts codemirror/fhem_codemirror.js hausautomatisierung-com/custom.js`
`attr WEB roomIcons Save.config:message_attention`
entfernen.
Dann sollte nichts mer von dem theme übrig sein.

Das entfernen der attribute sollte allerdings auch reichen um das theme umstellen zu können.
