### ISSUE TITLE
DBPlan Modul

### ISSUE THREAD

**Issue by andreas-vester** [JoschaMiddendorf/fhem-docker#38]
Hallo Joscha,

kannst du bitte überprüfen, ob das Perl Modul HTML:Table Extract im Container enthalten ist. Dies wird für das FHEM Modul DBPlan benötigt.
Infos unter https://wiki.fhem.de/wiki/DBPlan

Danke und viele Grüße
KraxelHuber

**Comment by JoschaMiddendorf** [comment]
wird gemacht

**Comment by JoschaMiddendorf** [comment]
Ist installiert, Update steht in Release 2.1.4 sowie in der aktuellen beta und master/latest zur verfügung.

#### If you appreciate my work and if you use and like these container, consider to make a little donation.

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=L98P3QMZFDHCN)

**Comment by andreas-vester** [comment]
Läuft :-)
Danke!
