### ISSUE TITLE
Holiday File wird nach Update überschrieben

### ISSUE THREAD

**Issue by andreas-vester** [JoschaMiddendorf/fhem-docker#42]
Hallo Joscha,

ich nutze das "holiday2we"-Attribut innerhalb des Global Devices. Dafür habe ich die Datei nw.holiday im Verzeichnis /volume1/docker/fhem_docker/FHEM/holiday auf meinem NAS bearbeitet. Dieses Verzeichnis ist gemappt auf /opt/fhem. Wenn ich innerhalb von FHEM ein Update durchführe und mittels "shutdown restart" neu starte, wird die Datei auf meinem NAS überschrieben. Meine Änderungen gehen dann verloren. Wie ist hier am besten vorzugehen?

**Comment by JoschaMiddendorf** [comment]
Der Container nimmt an dem /FHEM Verzeichnis keine Änderungen vor.
Falls das Thema noch aktuell ist hilft dir eventuell dieser thread weiter.
[https://forum.fhem.de/index.php?topic=90477.0]
Sorry dass ich jetzt erst reagiere. Der Issue ist bis jetzt nicht zu mir durchgedrungen.

**Comment by andreas-vester** [comment]
Danke für den Link. Ich hatte seinerzeit schon als Lösung ein eigenes Holiday File erstellt, welches auch nicht überschritten wird.
